### ISSUE TITLE
Able to prioritize the cards in each column

### ISSUE THREAD

**Issue by ericajones305** [funretro/distributed#102]
It would be great if we were able to move the cards in each of the cards in priority order

**Comment by glauberramos** [comment]
@ericajones305 the problem with this idea is that it will break the current "Order by votes" or "Order by created date" functionality. How do you think this should work together with the "order by"? 

Maybe we add a new value on the dropdown called "default" or "prioritized"?

**Comment by glauberramos** [comment]
One problem with this feature is that it is not compatible with the layout of merging cards, because right now the drag-drop is used for merging the cards. If we want to change the order, the interface probably would need to change.
