### ISSUE TITLE
Webpack Developer Workflow

### ISSUE THREAD

**Issue by pamo** [funretro/distributed#105]
@brunapereira @glauberramos and anyone else interested in contributing:

I spoke with @glauberramos about the branch I've been messing around with: 
https://github.com/funretro/distributed/tree/webpack

The goal is to get rid of gulp and introduce webpack + es6 + newer version of angular?

Right now the plumbing is in place to do local development and run tests (I've included a rough to-do list in the Read Me). However, this task won't be a simple copy and paste to get the functionality the same as master. 

I wanted to get your thoughts and maybe support in refactoring the code. The main controller is getting way too big and it's kind of hard to decipher how some of the functionality is working. 🙈 

I also think with the refactor, it will be easier to handle issues with the UI, e.g. #26 and we can also start thinking about a different way to store data apart from firebase (perhaps another repo for a socket io server we can host somewhere).

**Comment by brunapereira** [comment]
Interesting!

I would love to have a 'live' conversation about it, what do you think? I want to help with de migration but we need to define what we'll change and how to do it.

**Comment by pamo** [comment]
Buen idea @glauberramos y yo podemos coordinar un video chat contigo. Que hora sirve para ti?

**Comment by brunapereira** [comment]
Cualquier dia por la noche, después de las 19:40. Cuando prefieren @glauberramos  y @pamo?

**Comment by glauberramos** [comment]
:D Hablamos entonces jueves

**Comment by pamo** [comment]
[] redo firebase auth
[] look at firebase 2 features
[] see if we can host on digital ocean
[] see if we can host on linode
[] implement routing to board controller
[] extract board directive
[] extract column directive
[] extract card directive

**Comment by pamo** [comment]
@brunapereira firebase has hosting included 😂

**Comment by glauberramos** [comment]
I will close this and add the separate issues for the tasks.
