### ISSUE TITLE
Provide ability to add a picture

### ISSUE THREAD

**Issue by maryellen163** [funretro/distributed#106]
Many retrospectives are based around a picture (hot air balloon, speed boat, etc).  It would be nice if we could link to a picture and have it show above the columns.  Bonus points if there were some stock photos to insert that relate to some of the fun retrospective ideas.

**Comment by glauberramos** [comment]
I found this one that fulfil this need: 
http://suricatoagil.com/

**Comment by glauberramos** [comment]
I don't think this would work with the current layout of the retro. This approach works better with with a drag interface. I am going to close it for now.
