### ISSUE TITLE
Deploy to Firebase Hosting

### ISSUE THREAD

**Issue by pamo** [funretro/distributed#109]
https://firebase.google.com/docs/hosting/deploying

**Comment by cawlin** [comment]
Is deploying the code in current state possible? Anything that needs to be addressed that isn't currently documented?

Sorry fi this is the wrong place to ask this question :)

**Comment by glauberramos** [comment]
@cawlin I don't know exactly because I never tried firebase hosting. Can you give me your thoughts why do you think this is a good idea? Right now we are using github pages and as far as I know it is working pretty well, and it is free.

**Comment by cawlin** [comment]
@Glauberamos oh I thought this was for hosting the distributed app (like self hosting a version on firebase).

I am looking to host my own instance of distributed and saw this before trying!

**Comment by glauberramos** [comment]
Oh I see, this could be as well for self hosting, but I think it was created for hosting the current online tool that we have hosted on github pages right now.
