### ISSUE TITLE
Support markdown

### ISSUE THREAD

**Issue by licarth** [funretro/distributed#113]
It could be fun and useful to be able to render markdown.

**Comment by pamo** [comment]
What would the usecase look like?

**Comment by Roshanjossey** [comment]
@pamo: I can think about scenarios like having emphasis to text like bold or italics.
Having said that I don't think that would add much value. As far as I understand, non formatted text is sufficient for what we post on retro cards

**Comment by glauberramos** [comment]
I agree that only text is enough for now for funretro.

The main idea about the app is to keep it simple, that means, to keep less functionality as possible.

So I will close this for now.
