### ISSUE TITLE
Make hash bigger and more secure

### ISSUE THREAD

**Issue by glauberramos** [funretro/distributed#115]

**Comment by brunapereira** [comment]
You mean the userId? Whats the motivation?

**Comment by glauberramos** [comment]
the userID now has 5 characters, it is pretty to create an automated script and find every board ever created on funretro. I wanted to increase to maybe 7 or more so it is harder do discover boards. What do you think @brunapereira ?

**Comment by brunapereira** [comment]
Makes sense!
