### ISSUE TITLE
bug: create board with empty name

### ISSUE THREAD

**Issue by glauberramos** [funretro/distributed#125]

**Comment by Roshanjossey** [comment]
I also came across this. Here are some steps to reproduce this.

  * go to http://funretro.github.io/distributed/
  * click on new board button
  * click on create button (Do not enter title)

You'll be taken to a blank board (no default columns) new column will not work as expected

**Comment by glauberramos** [comment]
Hello @Roshanjossey, thanks for pointing that out. The idea of this bug is to fix the exactly issue that you reported :D

Thanks

**Comment by Roshanjossey** [comment]
Hey @glauberramos: I shared the scenario to help anyone who might be interested in fixing this bug. I believe adding such a description would give others more context. I love the way hoodie handles this. Here's an [example](https://github.com/hoodiehq/camp/issues/95)

I'd like to take a stab at this issue.

**Comment by glauberramos** [comment]
Please go ahead @Roshanjossey :D

We are currently working with pull requests and code reviews, so you can go ahead and fork and create a pull request.

Thanks
