### ISSUE TITLE
BUG: card layout in firefox is broken

### ISSUE THREAD

**Issue by glauberramos** [funretro/distributed#126]
<img width="1273" alt="screen shot 2016-12-26 at 3 31 41 pm" src="https://cloud.githubusercontent.com/assets/559434/21484840/7f206aa8-cb80-11e6-9a0c-c7ff17d89aa8.png">

**Comment by Roshanjossey** [comment]
@glauberramos: I understand that you're mentioning the card in `Action items`. I see that the voting div is overlapping with the edit icon above it.

One possible solution can be to provide a `min-height` to the whole div. Do you have some other solutions in mind?

**Comment by glauberramos** [comment]
I think the min-height may help. It's probably the more straight-forward solution.
