### ISSUE TITLE
License

### ISSUE THREAD

**Issue by chapmanjw** [funretro/distributed#127]
Anyway you could switch to the MIT license?

**Comment by glauberramos** [comment]
@chapmanjw can you explain more about why do you think this is the best option? (I really don't know a lot about licenses)

**Comment by chapmanjw** [comment]
You can read about the GPL license here: https://en.m.wikipedia.org/wiki/GNU_General_Public_License

Basically my company doesn't let us fork and modify GPL software (not sure of all the reasons why), but I think it has to do with having the keep strictly to the GPL license, rather than being able to license forks differently, etc.

**Comment by glauberramos** [comment]
For now I don't have plans to change it. You can fork on your personal account and work on it or use our public app on funretro.github.io/distributed.

Thanks,
Glauber
