### ISSUE TITLE
Add and use labels for issues to make project contributor friendly

### ISSUE THREAD

**Issue by Roshanjossey** [funretro/distributed#129]
I've started working on project to help beginners get started on open source contributions. 
https://github.com/Roshanjossey/first-contributions

One thing I learned by talking to my users is that people gets interested in starting to contribute to a project if they recognise easy issues to solve. One way to make this apparent is to use labels for issues. I've seen project using labels like `beginner friendly` and `good first task` for such cases.

We already have a `help wanted` label by default. I bet it'll attract more contributors if we use such labels for issues

**Comment by glauberramos** [comment]
Done

**Comment by Roshanjossey** [comment]
@glauberramos: It's awesome that you created `beginner friendly` label and started using it.
I've added this project to my list in first contributions too.

Do check it out at https://github.com/Roshanjossey/first-contributions and gimme some feedback
