### ISSUE TITLE
Comments on cards

### ISSUE THREAD

**Issue by jffrybrwn** [funretro/distributed#132]
It'd be nice of people could leave anonymous comments on cards in addition to voting.

**Comment by glauberramos** [comment]
@jffrybrwn  which use case do you think this would be useful? Could you explain further? 

Ideally all comments should happen on the retro meeting itself, and if there is anything important that need followup, it should be created on the "Actions" column.

**Comment by vhetet** [comment]
@glauberramos I think it could be really useful when a cards is not really clear or when a user want to add something to this card.
During my team retro today one of the card was not really clear and I was thinking that comments would be useful to as what this card exactly meant.

**Comment by glauberramos** [comment]
@vhetet If a card is not clear, why not just rewrite it? That's the point of anyone being able to write on the cards.

**Comment by vhetet** [comment]
ok but if you don't know what the person meant in the first place you can't rewrite it

**Comment by glauberramos** [comment]
Just trying to understand better your need here.

Were you doing a live retrospective? Everybody together on the same call? Is asking the person that wrote an option?

**Comment by vhetet** [comment]
What we usually do is adding the card before the retro so we are not talking at this time. And then during the retro we sort them and prioritize them depending on the vote they got.

**Comment by glauberramos** [comment]
Yeah that's make sense. I didn't know people were doing async retrospectives. Most of the retrospectives I saw and participated were live. Everybody writing at the same time, so it was easy to just ask someone about a card. Thanks for sharing your experience.

**Comment by vhetet** [comment]
That's what we were doing but we found out we were spending too many time talking about what was the card and not enough about how to tackle the problem on the card. We are still experimenting though but it's working pretty well so far.
Anyway thank you for building that tool, it's pretty cool.
