### ISSUE TITLE
Import/preseed cards

### ISSUE THREAD

**Issue by varac** [funretro/distributed#138]
I have a textfile with say 30 options that I'd like to vote for using funretro.
I'd like to import these cards so our team can easily vote, without manually creating each cards one by one.

**Comment by mrzinger** [comment]
I suppose csv format can be used for this. It easy to use, open and accessible. What do you think?

**Comment by varac** [comment]
awesome!

**Comment by mrzinger** [comment]
The feature is implemented, but stuck on Pull request review. You can either take the corresponding branch https://github.com/mrzinger/distributed/tree/138-import-cards or add more votes to it to get it back from "idea" to "feature"

**Comment by glauberramos** [comment]
It is a feature now, I removed the idea label.

**Comment by DaddyBA** [comment]
Is this usable now?

**Comment by glauberramos** [comment]
It is only on master, but it will be deployed to production soon.

**Comment by glauberramos** [comment]
I just deployed to production 👯‍♂️
