### ISSUE TITLE
Change color of the columns

### ISSUE THREAD

**Issue by glauberramos** [funretro/distributed#142]
The idea is to be able to change the default color of the columns, so we can avoid problems like "what went nice" column in red.

**Comment by glauberramos** [comment]
@tiagomtotti just created this issue 💃  no pressure hehehe

**Comment by cawlin** [comment]
Just noodling on how this could look. Forgive me for playing with a few other changes in the same area. I've been thinking about how "adding" new items could be more prominent and "removing" columns would be more obvious if it used the same "trash" icon as items.

![colour-picker](https://user-images.githubusercontent.com/370173/31298368-1ab72f82-aaa7-11e7-80ea-f4173e3c0926.png)

![full-view](https://user-images.githubusercontent.com/370173/31298374-1f677f28-aaa7-11e7-94c8-60e60bc4e668.png)

**Comment by glauberramos** [comment]
I like this design but I am not sure if the "+ add new" button is it the best place. It looks a little out of the place there. I already had an idea of having a textbox after the column name that you can type and after you hit enter the card is created. So in the case there is no need for buttons.

**Comment by cawlin** [comment]
@Glauberamos Interesting - sure let me see what that would look like after this weekend. I don't like my "add new" button much either, I just wanted to make a bigger more clear target than the current blue plus icon.

What do you think about the header and the colour picker? Is this along the lines of what you were imagining?

**Comment by cawlin** [comment]
@glauberramos is this sort of what you had in mind?

![text-boxes](https://user-images.githubusercontent.com/370173/31558184-23e017f6-b009-11e7-99b8-e1b06a94d2c8.png)

**Comment by glauberramos** [comment]
Yeah that was the general idea, but without the done button and just a single line. What do you think about it? It may improve the experience because people will not see others typing when the card is being created.

**Comment by cawlin** [comment]
@Glauberamos yeah we can jam on the the button placement and how "adding" a new card works in general. 

Here's another quick take at it. Putting each column inside a container and full width buttons:
![column-full-width](https://user-images.githubusercontent.com/370173/32525234-a8c97ae4-c3e0-11e7-94b5-f98c4ec42c39.png)

**Comment by glauberramos** [comment]
Another idea:

I prefer the color selection just flat color, without the border. In this idea here the delete button is hidden by default:

<img width="288" alt="screen shot 2017-11-07 at 23 29 04" src="https://user-images.githubusercontent.com/559434/32527084-b6c7f0f2-c413-11e7-859b-96c10ab1f702.png">

When you hover the delete button shows up:

<img width="293" alt="screen shot 2017-11-07 at 23 28 31" src="https://user-images.githubusercontent.com/559434/32527091-bd757294-c413-11e7-96f2-d4c7dec2e208.png">

**Comment by DaddyBA** [comment]
My 2 cents
I like the border around the color as it feels more like a button. 
I like the hidden trash can
I like the full width add button.

**Comment by prateek3255** [comment]
I want to work on this issue. Should I work according to the last mockup provided by @glauberramos?

**Comment by glauberramos** [comment]
Hello @prateek3255, I will close this issue now because I already did the code on https://funuretro.io. I will just have to port to here.
