### ISSUE TITLE
Hide the vote count while participants are voting

### ISSUE THREAD

**Issue by alvarocavalcanti** [funretro/distributed#146]
When requesting participants to start voting I would like to have the vote count to be hidden.

Ideally, the board could have a "start voting" button that would hide the vote count for the cards. This button would become "stop voting" then, and its state should be shared across all sessions.

This would prevent a voting bias and thus reflect more accurately the group's opinions.

**Comment by glauberramos** [comment]
I like this idea,

There is only one challenge because we currently don't have a administrator for the retros, so everyone would be able to start voting and stoping it at any time.

@alvarocavalcanti do you think that would be a problem?

**Comment by alvarocavalcanti** [comment]
@glauberramos I don't think so. I mean, we already have this situation where anyone can create, rename or even delete columns and cards. The users tend to use it fairly, and I don't see why they wouldn't do so with this new feature.

And if you look closely, this is a much less sensitive feature since it only involves hiding/showing information, not manipulating it. 😄 

Oh, and by the way, maybe the button could read simply "hide votes"/"show votes".

**Comment by glauberramos** [comment]
@alvarocavalcanti makes sense, I am going to implement it in the next week or so. Since it looks very simple :D

**Comment by DaddyBA** [comment]
Hide votes/show votes feels different than start/sto. But I guess stop makes it seem like voting function will actually be disabled, so I see the problem with implementing this

**Comment by glauberramos** [comment]
@DaddyBA what is the problem with implementing this? I didn't understand

**Comment by DaddyBA** [comment]
Hiding and showing vote counts on the cards to avoid "grandstanding " solution makes sense. 
Start voting and stop voting would be more challenging. Depending on the messaging, it could also be confusing. You would probably need 3 states. "Voting has not begun ", "Voting is in progress ", "Voting has ended " as well as a way to switch between states. Some will likely close voting early and eventually ask to have a re-open voting option. And other people will want current functionality of always open voting. 
Hiding and showing the count is Minimally Viable Functionality

**Comment by alvarocavalcanti** [comment]
Oh, nicely put. That makes totally sense. :)

Em seg, 1 de mai de 2017 às 09:30, DaddyBA <notifications@github.com>
escreveu:
