### ISSUE TITLE
Ability to change max number of votes once the board is created

### ISSUE THREAD

**Issue by glauberramos** [funretro/distributed#150]
After the board is created, it should be able to change maximum number of votes per user
Also we should have a option to disable of not max number of votes on board creation or after board is created.

**Comment by sherfin94** [comment]
I'm working on it

**Comment by sherfin94** [comment]
@glauberramos , what should happen when a user have already cast more votes than the newly set number of maximum votes allowed ?

**Comment by glauberramos** [comment]
@sherfin94 I think it is fine how it is working right now. It should show "remaining votes: 0" and it should only allow the user to vote after it removes enough votes.
