### ISSUE TITLE
Author of a card

### ISSUE THREAD

**Issue by glauberramos** [funretro/distributed#153]
One idea that some people ask is to be able to add a author of a card. Do you think this would be useful? Maybe we could have a separated field for it.

**Comment by mrzinger** [comment]
Certainly it is.
How about this way?
![image](https://cloud.githubusercontent.com/assets/1550163/24660177/2711e568-194f-11e7-81f6-9f3c95dc2836.png)

**Comment by glauberramos** [comment]
It should be something like this @mrzinger, but since this is only a "idea" so far, I still not sure if this is needed for the majority of the users of funretro. I am not sure if this should be implemented.

**Comment by glauberramos** [comment]
Some other ideas for UI:

<img width="272" alt="screen shot 2017-04-04 at 15 03 22" src="https://cloud.githubusercontent.com/assets/559434/24671489/0d450d4c-1948-11e7-9bd6-fcd1af216788.png">

<img width="273" alt="screen shot 2017-04-04 at 15 03 59" src="https://cloud.githubusercontent.com/assets/559434/24671496/10a2bcdc-1948-11e7-8f3a-73db410ce5e5.png">

I would like to investigate first if this feature is really needed. Because in my experience with retros, you can just ask who wrote the card, and the author will just tell.

**Comment by DaddyBA** [comment]
Sometimes we use this for what I call a 'living retro '. I am using it for a multiple-team retro (40-50 people, multiple sites)
Having an anonymous version is still important, but a version like this would be very helpful.  even in small but distributed teams

**Comment by samantharogers8** [comment]
My team would definitely benefit from showing authorship! We're co-located and often have people in and out of our retros-- this would cut down on the "Who wrote this?" silence

**Comment by apriendeau** [comment]
A thought to this would not necessarily be authors but each connection could be a different color card? ¯\_(ツ)_/¯ 

We kept hijacking each other's cards.

**Comment by cbier1** [comment]
We just add our names in the card contents. Usually by simply adding our initials at the end

![image](https://user-images.githubusercontent.com/19910177/43326236-50c6339a-9186-11e8-815c-8f1635d8bae3.png)
