### ISSUE TITLE
Enter key can't be used to submit forms

### ISSUE THREAD

**Issue by Roshanjossey** [funretro/distributed#154]
🐞 **Problem**
  Currently in modals like creating board and columns, enter key can't be used to submit when focus 
  is in input fields. Users will have to press tap to focus on `Add`/`Create` or click with mouse.
 
🎯 **Goal**
It is a standard pattern to submit a form by clicking enter key in input field. We wanna do that

💡 **Possible solutions**
On press of enter/return key in input field, submit form

📋 **Steps to solve the problem**

 * Comment below about what you've started working on.
 * Add, commit, push your changes
 * Submit a pull request and add this in comments - Addresses #<put issue number here> 
 * Ask for a review in comments section of pull request
 * Celebrate your contribution to this project 🎉

**Comment by alanjsph** [comment]
I've started working on adding an key press event listener to solve the issue

**Comment by glauberramos** [comment]
@Roshanjossey I really liked the issue format here :D Well explained and documented.

@alanjsph I will take a look on the PR now.
