### ISSUE TITLE
Missing Contributor guideline

### ISSUE THREAD

**Issue by mrzinger** [funretro/distributed#161]
I see a few people are contributing to the project from time to time. So it looks to me it would be good to have simple guidelines for the contributors describing some basic rules like:
- Coding guidelines
- Branching guidelines (is there branches naming convention in place?)
- Definition of done (what should be done for the feature to pass Pull request)
- Maybe basic architecture guidelines.

It shouldn't be thorough and comprehensive description and in most cases will refer to some other 3rd party guidelines, but I think even basic intro would improve the PRs quality and reduce amount of time for review.

**Comment by glauberramos** [comment]
@mrzinger do you have any good example of other opensource projects that I can get inspiration from?

**Comment by mrzinger** [comment]
Well, https://github.com/Microsoft/vscode is not bad. 
Of course it is much bigger project however the guidelines look pretty lightweight.
