### ISSUE TITLE
Enter creates card, cmd-enter adds a new line

### ISSUE THREAD

**Issue by katharinekerr** [funretro/distributed#167]
Currently, enter adds a new line and cmd-enter creates the card. I think it's more intuitive if enter creates the card and cmd-enter adds a new line. Also since enter now creates a column and creates a new board when the dialogs are open. These actions are used in Facebook messenger and iOS iMessenger. (Although I know gmail uses the current actions).

👍  Great project!

**Comment by DaddyBA** [comment]
Maybe shift+enter?
Cmd+enter seems out of sync with other keystrokes in other apps

**Comment by katharinekerr** [comment]
Shift-enter actually sounds better
