### ISSUE TITLE
Fiz mobile layout

### ISSUE THREAD

**Issue by glauberramos** [funretro/distributed#170]
<img width="323" alt="screen shot 2017-04-20 at 12 42 13" src="https://cloud.githubusercontent.com/assets/559434/25239612/d5a8fb38-25c6-11e7-96f7-64996fcd41a7.png">

**Comment by DaddyBA** [comment]
Although I don't like this layout on mobile, what is the acceptance criteria. What is the specific problem being solved?

**Comment by glauberramos** [comment]
@DaddyBA the problem is mainly caused by the "remaining votes" functionality, where it is breaking the layout as you can see on the picture above.

**Comment by DaddyBA** [comment]
Mostly I don't like seeing 1 column at a time. Might not be feasible to layout multiple columns
