### ISSUE TITLE
Extract config from source code

### ISSUE THREAD

**Issue by miketwo** [funretro/distributed#173]
The firebase url `https://blinding-torch-6662.firebaseio.com` shows up in mutliple places in the code. It would be better to get this config either from the environment like:
```
var firebaseUrl = process.env.FIREBASE_DB_URL;
```
...or dependency-injected like:
```
.service('FirebaseService', [..., 'myApp.config', function (..., firebaseUrl) {
```
This allows for easier development. Devs can change a hidden config file or environment var instead of modifying source code.

There's a lot of ways to do it. Here's 2 options:
 - Use [gulp-ng-config](https://www.npmjs.com/package/gulp-ng-config) to generate an injectable Angular module.
 - Use [gulp-env](https://www.npmjs.com/package/gulp-env) to populate `process.env`.

**Comment by glauberramos** [comment]
I added a config file and all references to the firebase config were removed from the code
