### ISSUE TITLE
Unable to change cursor position in text areas in Firefox

### ISSUE THREAD

**Issue by anton-gorbikov** [funretro/distributed#186]
Steps:
1. Open Firefox;
2. Create new board and add new message;
3. Type some text and try to change cursor position using mouse;

Actual Result:
- It's not possible to change cursor position or select text using mouse;

Expected Result:
- It's possible to change cursor position or select text using mouse;

Possibly it's the result of known FF issue: https://bugzilla.mozilla.org/show_bug.cgi?id=800050

**Comment by vhetet** [comment]
why is this bug still open? It looks like @anton-gorbikov fixed it :)
