### ISSUE TITLE
Add ability to filter cards

### ISSUE THREAD

**Issue by anton-gorbikov** [funretro/distributed#188]
It's a nice to have feature to be able to filter cards. For example if we talking about standard column "to improve" and "action items". Sometimes action items are based on things that should be improved. Hence I want to have an ability to display only "related" messages on the screen and focus on them.

To achieve this I can add prefixes to messages, e.g. "A:", "01:", etc. and then use these prefixes as filters.

**Comment by kitsuphat2528** [comment]
Follow the steps. Thank you.
