### ISSUE TITLE
If a board is deleted and an user try to access it, show a better message

### ISSUE THREAD

**Issue by glauberramos** [funretro/distributed#199]
Not it keeps loading forever

**Comment by pankti-m** [comment]
I will pick this up and try to work on the fix.

**Comment by PixleProgrambetaxl** [comment]
+1

**Comment by pamo** [comment]
Has this been addressed already?
![image](https://user-images.githubusercontent.com/784889/46900241-dec72280-ce53-11e8-8f11-79dda88e9ad3.png)

**Comment by glauberramos** [comment]
The website funretro.io has a different codebase now that has been forked from this repository. I fixed this at this new repository but I still need to bring the changes back to this repository.
