### ISSUE TITLE
Need a bit more help from the Readme.md on Firebase setup

### ISSUE THREAD

**Issue by francisluong** [funretro/distributed#210]
Hi,

I'm trying to get my own copy working on my box but I'm not clear on how to get the API key from firebase.  

I have setup a firebase project.  If I choose [Settings Gear] -> [Project settings]: 
 - I can find a Web API Key under `General`.
 - I can find `Server Key`, `Legacy Server Key`, and `Sender ID` under cloud messaging.

Which settings do I use to populate the [firebaseInitialization.js](https://github.com/funretro/distributed/tree/5be50aa78052a8168934338e00b69d597184094e) file, most specifically, `apiKey`?

Thanks!

**Comment by glauberramos** [comment]
You no to click on "Add firebase to your web app"

<img width="617" alt="screen shot 2017-08-30 at 03 16 47" src="https://user-images.githubusercontent.com/559434/29857961-bcc8c9b8-8d31-11e7-991f-64a02c4093b9.png">

And copy everything into firebaseInitialization.js.

I hope that helps you.
