### ISSUE TITLE
Instructions on how to deploy to github pages

### ISSUE THREAD

**Issue by glauberramos** [funretro/distributed#214]

**Comment by abiduzz420** [comment]
Heyy @glauberramos @pamo could you elaborate regarding the subject of the issue ? Thanks!

**Comment by gramster** [comment]
github pages is for static sites. This would require removing the dependency on node so that everything ran client-side.

**Comment by gramster** [comment]
Oh, and everything would be public on gh-pages including things like API keys. So its a nice idea but not realistic.
