### ISSUE TITLE
Censor text when editing a previously saved card

### ISSUE THREAD

**Issue by BlexBaker** [funretro/distributed#215]
## Description
Related to closed issue #63 (Be able to write cards without everyone see it before you save). Currently, text is censored when typing a new card and visible to everyone after it's saved. However, if you edit that card, then your text is visible as you modify it. I'd suggest censoring the text any time it's being edited. 

## Motivation
The motivation is the same as the original issue- to protect people's privacy as they try to form ideas. Also, from a UX perspective, I think the behavior would be more consistent/expected if cards were censored any time text is being added.

**Comment by pamo** [comment]
I can take a stab at this.

**Comment by BlexBaker** [comment]
Hi @pamo I saw you assigned yourself to this issue, so I wasn't intending to address it in my pull request which responds to #151. I'm only toggling censor text when cards are created (the current behavior) not any time they're being edited. 

It occurs to me now that my variable names might be misleading. But I had meant to leave my code open to allow you to add the changes related to #215. Sorry for the confusion, and thanks for the code review! 😄

**Comment by pamo** [comment]
Ohh gotcha! Cool I can still pick this up once your PR goes through.

**Comment by glauberramos** [comment]
Hey guys, I thought of this issue before, but I couldn't figure out a way to disable the edit view if a user just closes the site without clicking on save. We don't have login right now, so we can't rely on session. Any idea?

**Comment by glauberramos** [comment]
I did it and it is on production already with #151
