### ISSUE TITLE
Need some help setting up local environment- can't create boards

### ISSUE THREAD

**Issue by Acrylami** [funretro/distributed#217]
Hi, I'm just getting started with open source and would appreciate help in getting started.
I've installed Node JS, Gulp, and set up the Firebase, but when I go to my http://localhost:4000 and attempt to create a new board it just loads forever....

Could anyone assist me in fixing this? I feel as if I'm missing something.

**Comment by BlexBaker** [comment]
@Acrylami Do you see any errors in your console when this happens? I had this same problem when I didn't have my firebase authentication set up correctly. If that were the case, you'd see an error related to your API key.

**Comment by glauberramos** [comment]
@Acrylami did you add your js/vendor/firebaseInitialization.js with your firebase configuration?

**Comment by pamo** [comment]
Honestly, the documentation is not very clear around where you need to go in the firebase console to get started for new contributors.
For example, you have to create a new app and then go to project settings to find `YOUR_PROJECT_ID` and `YOUR_API_KEY`
![image](https://user-images.githubusercontent.com/784889/31858394-58f7c008-b6ab-11e7-8733-23a011c46f67.png)

and then `YOUR_MESSAGE_ID` is referred to as `Sender ID` under the Cloud Messaging tab in the settings panel.
![image](https://user-images.githubusercontent.com/784889/31858405-a066ca60-b6ab-11e7-9459-3a6b4f4cb3c5.png)
