### ISSUE TITLE
Render Hyperlinks inside a card

### ISSUE THREAD

**Issue by viniciusrdacosta** [funretro/distributed#218]
## Description

Add capability to render links inside a card.
Would be good to have a way to add hyperlinks inside a card.

Currently when I added a external link inside a card funboard displayed it as a text

<img width="1272" alt="screen shot 2017-10-18 at 14 32 21" src="https://user-images.githubusercontent.com/1073869/31730607-354eab4a-b411-11e7-8260-868d489d5bff.png">

## Motivation
I want this feature because my team has this necessity when doing retrospective in this way
Sometimes we need to make a reference to an external source of information and have a link inside a card will make our life easier. Today we need to copy and paste each link manually.

**Comment by glauberramos** [comment]
That's a nice suggestion, thanks

**Comment by Thirdoptics** [comment]
I'll have a go at implementing this, seems like a fun basic problem to tackle.  Should I just start with basic parse and replace for http links or would there eventually be a need for more markup options like bold, italics, quotes, etc?

**Comment by glauberramos** [comment]
I think we can start with links first

**Comment by pamo** [comment]
I picked this up @viniciusrdacosta @Thirdoptics @glauberramos, hope you don't mind!

**Comment by Thirdoptics** [comment]
Thanks for picking this up @pamo, I'd missed this was an angular based project before I opened my mouth, would've been a good excuse to stretch the Javascript muscle, but probably best you picked it up.
