### ISSUE TITLE
[Setting up funretro] Signup issue while creating new board

### ISSUE THREAD

**Issue by Roshanjossey** [funretro/distributed#228]
Hey @glauberramos, long time

## Description

While setting up funretro, On creating a new board, I get a bad request error

## Expected Behavior

Retro board should be created on clicking create

## Actual Behavior

There is a bad request error

```
POST https://www.googleapis.com/identitytoolkit/v3/relyingparty/signupNewUser?key=%20<my-api-key>%20 400 ()

Create user failed:  
* ro {code: "auth/operation-not-allowed", message: "The given sign-in provider is disabled for this Fi…under the sign-in method tab of the Auth section."}
    * code : "auth/operation-not-allowed" message : "The given sign-in provider is disabled for this Firebase project. Enable it in the Firebase console, under the sign-in method tab of the Auth section." __proto__ : Error 
```

I understand this is caused because of a signup problem. I don't remember getting this when I was setting it up 1 year back.

## Suggested solution

I could solve this problem by enabling `Email/Password` sign-in-method from Authentication section of firebase project.

It might be good to specify this in setting up section.

**Comment by pankti-m** [comment]
I am new to open-source and would like to make this my first contribution.  From the description, it seems like this involves a documentation change?

**Comment by Roshanjossey** [comment]
@pankti-m, great to see you here. Yes, it is a documentation change. I'd urge you to set up funretro and find out why this is an issue. That way you'll have clarity on solution.

**Comment by juventinoromero** [comment]
Hi! Is this issue resolved?

**Comment by pankti-m** [comment]
Thanks.

I am getting some errors when trying to setup the environment.

Running 'gulp' throws an error - 
"Error: Node Sass does not yet support your current environment: Linux 64-bit with Unsupported runtime (57)"

'npm install' in the repo did finish but had some warnings - 
npm WARN optional Skipping failed optional dependency /chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.1.3

Can I get details about the supported OS, node versions etc?

**Comment by Roshanjossey** [comment]
@pankti-m, could you please try solutions in https://github.com/sass/node-sass/issues/1651 to fix problem with node-sass?
I think warnings in `npm install` is okay.

I'm not sure if we have a supported OS, node versions recorded somewhere.
Rule of thumb would be to go with latest node
I'm using macOS and node 7.7.4 for funretro development.

**Comment by pankti-m** [comment]
Thanks for the info.  I was able to deploy the app and can see the error on the web console when creating a new board.  Will work on the patch next.
