### ISSUE TITLE
Add button disappears

### ISSUE THREAD

**Issue by cbier1** [funretro/distributed#255]
## Expected Behavior
The "+" button should not disappear when you click on it

## Actual Behavior
When you click on the "+" button it disappears and is replaced by a new card. The only way that I could find to get the "+" button to re-appear was to click the "Add" button on the newly created card. 

## Why is this a problem?
We tend to add multiple cards per person per column so this bug makes it impossible to do that without showing our card contents to our teammates prematurely. This wasn't a problem before the most recent UI changes

**Comment by glauberramos** [comment]
From what I understand you used to keep all cards in "edit" mode and only close them after everyone finished writing the cards. So no-one would see other people cards.

Correct?

**Comment by glauberramos** [comment]
Fixed, you can now add multiple cards before showing to people.
