### ISSUE TITLE
Include Database Permissions in Local Environment Setup Instructions 

### ISSUE THREAD

**Issue by bccurry** [funretro/distributed#258]
## Description

Include Database Permissions in Local Environment Setup Instructions to Fun Retro

## Motivation

I want this feature because I was unable to create a new board without modifying the firebase database read/write permissions. The permissions are initially set to false and will need to be set to true in order for the application to interact with the database.

<img width="1351" alt="screen shot 2018-08-21 at 8 45 36 pm" src="https://user-images.githubusercontent.com/3373972/44438094-38614e00-a583-11e8-9df8-e7db0cb465af.png">

**Comment by atroutt** [comment]
I'd recommend at least having the rules require a logged in user
```{
  "rules": {
    ".read": "auth != null",
    ".write": "auth != null"
  }
}```

**Comment by glauberramos** [comment]
Done
