### ISSUE TITLE
Unable to create first board

### ISSUE THREAD

**Issue by clawOndeck** [funretro/distributed#259]
Hi,

We are trying to set up a FunRetro and got the app running. However, we are not able to create a board.

Clicking on new Board with a random name and hit Create will lead us to a "connecting" state as shown in the screen shot below:

![screen shot 2018-09-18 at 1 37 37 pm](https://user-images.githubusercontent.com/20110423/45705640-1a6a1780-bb48-11e8-8f27-1b01b2b8fc92.png)

Are they any log that we can use to debug what is wrong in our setup?

Also, what is "messagingSenderId" in js/vendor/firebaseInitialization.js?

There is no such field in the Firebase project settings.

Please help.

Thank you so much.

**Comment by clawOndeck** [comment]
Hi,

Can we please get some support this is question? I found another similar question  https://github.com/funretro/distributed/issues/217 and has verified that our configurations are correct.

Any help is appreciated.

Thanks.

Chuan

**Comment by glauberramos** [comment]
I will take a look on it and let you know.

**Comment by clawOndeck** [comment]
Thanks. I saw another thread about modifying database rules. Now when I create the board I can see the data in the Firebase database, but front end is still spinning as in screen shot.

![screen shot 2018-10-05 at 11 40 47 am](https://user-images.githubusercontent.com/20110423/46545200-a9d73080-c893-11e8-9305-f58ed9214129.png)

**Comment by ilconfa** [comment]
same problem :(

**Comment by jmeadsync** [comment]
Having the same issue....confirmed firebase settings and data is created in the database, but unable to retrieve (just see the spinner and errors like:
```
vendor.js:1 TypeError: Cannot read property 'nb' of null
    at Qe.g.ya (vendor.js:1)
    at new Pe (vendor.js:1)
    at Xg.g.Nb (vendor.js:1)
    at ah.Nb (vendor.js:1)
    at Fh (vendor.js:1)
    at U.g.gc (vendor.js:1)
    at Object.init (vendor.js:1)
    at new n (vendor.js:1)
    at n (vendor.js:1)
 at Object.getBoardObjectRef (main.js:825) "Possibly unhandled rejection: {}"
```

**Comment by glauberramos** [comment]
This should be fixed now

**Comment by glauberramos** [comment]
Issue fixed
