### ISSUE TITLE
Mobile optimised version

### ISSUE THREAD

**Issue by glauberramos** [funretro/distributed#26]

**Comment by frontalicious-martijn** [comment]
Currently the app is not usable on mobile at all (iPhone). The announcement popup is in the way and cannot be closed.

For a first improvement it would be great just to be able to add or edit cards, someone on a desktop (the organiser) could move things around if needed.

**Comment by glauberramos** [comment]
I agree, currently the app is lacking mobile love.

Would you be interested in helping on it and create some pull requests on this issue here on github? It would be awesome.

Thanks,
Glauber

**Comment by glauberramos** [comment]
I made some improvements and now it's way easier to use on mobile.

I have a question: should we keep functions like "add column", "delete cards" on mobile version?

**Comment by pamo** [comment]
@glauberramos we should. Users would expect to be able to access all features regardless of device
