### ISSUE TITLE
Merging cards is sluggish

### ISSUE THREAD

**Issue by rokr** [funretro/distributed#260]
## Expected Behavior

Dragging on card over another and release mouse should merge both cards.

## Actual Behavior

Dragging one card over another one often doesn't let the cards be merged but sorts the dragged card above or below the targeted card.

**Comment by glauberramos** [comment]
I am aware of this issue, I will try to fix it as soon as I have time.

**Comment by derekprior** [comment]
I've noticed tht I can merge cards just fine in Chrome, but in Safari, attempts to merge cards always result in re-ordering.

**Comment by glauberramos** [comment]
Merge is improved now. @derekprior did you try to clear browser cache?
