### ISSUE TITLE
Being able to merge a card to another merged card

### ISSUE THREAD

**Issue by MaikuB** [funretro/distributed#266]
## Description

Add ability to merge a card to a card resulting from another merge

## Motivation

There are times where more than two team members will have the same idea. It would good to be able to merge all of their cards together and have the votes summed. 

## Expected Behavior

Currently, it's possible to merge cards A and B together to a single card (A+B). Dragging card C to that merge should get rid of card C and result in a single card that contains the details of A+B+C and the votes should be totalled.

## Actual Behavior

Card C just ends up positioned near the card that combined A and B

**Comment by glauberramos** [comment]
that's possible to do yes
