### ISSUE TITLE
[Setting up] New board stuck on loading indicator

### ISSUE THREAD

**Issue by nspassov** [funretro/distributed#267]
When I open funretro and try to create a new board, I get stuck on the loading indicator and nothing happens.
 - In gulp console there are no errors
 - All 80 gulp tests run successfully
 - In Firebase a new entry in the Authentication section is created every time I load the funretro page
 - In Firebase in the Storage section no entries are being created

I saw other posts here with the same effect, but I do not see any problem with my firebase config.

My setup: debian stretch, node 8.12, npm 6.4.1, gulp 3.9.1, gulp-cli 2.0.1, apache virtual host with reverse proxy (although I also tried on port 4000 with same result)

Any ideas about what is going wrong or what logs I can check?

**Comment by glauberramos** [comment]
Are you using latest code?

**Comment by nspassov** [comment]
Latest master

```
:~/funretro$ git log -n1
commit 55150a083f35d577181ccfd66545b74a2466e4a3
Author: Glauber Ramos <glauberamos@gmail.com>
Date:   Mon Oct 22 19:18:51 2018 -0300

    Add database rules```

**Comment by robpridham-bbc** [comment]
I might know why this is. The documentation could do with a bit of work.

I knew that I needed to permit access to the database. However, if you go to your Firebase project, and the database section, you get this:

![image](https://user-images.githubusercontent.com/26543551/51756213-66aa0300-20b8-11e9-89f5-4fb0af49d792.png)

So the rules are accessed in the tab below, right? No - wrong database type.

You need to pick 'Realtime Database' and then modify the rules there:

![image](https://user-images.githubusercontent.com/26543551/51756300-922ced80-20b8-11e9-99f4-49d41c6e5e36.png)

Related faults manifest in FunRetro as a Firebase permissions error in the Javascript console.

**Comment by nspassov** [comment]
@robpridham-bbc I owe you a beer!

**Comment by shtrom** [comment]
From quick tests, here's a better (i.e., not public to everything) ruleset:
```
{
  "rules": {
    "boards": {
      "$boardId": {
        ".read": "auth.uid == data.child('user_id').val()",
        ".write": "auth.uid == (data.exists()?data:newData).child('user_id').val()"
      }
    },
    "messages": {
      "$boardId": {
        ".read": "auth.uid == root.child('boards').child($boardId).child('user_id').val()",
        "$messageId": {
        ".read": "auth.uid == data.child('user_id').val()",
          
        ".write": "(auth.uid == root.child('boards').child($boardId).child('user_id').val())
          && (!data.exists() || auth.uid == data.child('user_id').val())
          && (!newData.exists() || auth.uid == newData.child('user_id').val())"
      	}
      }
    }
  }
}
```
