### ISSUE TITLE
Add number of cards on each column

### ISSUE THREAD

**Issue by glauberramos** [funretro/distributed#39]

**Comment by kartik2406** [comment]
Hey i came up with a basic solution to this. Do let me know if you want any UI changes.
![screenshot-2018-2-6 fun retro test](https://user-images.githubusercontent.com/24548910/35868453-9038a7e0-0b82-11e8-8794-cb0bf9f97677.png)

**Comment by glauberramos** [comment]
I think the UI is good. Do you think the number of cards is useful?

**Comment by kartik2406** [comment]
Not so much as the cards are visible directly.

**Comment by glauberramos** [comment]
@kartik2406 yeah, I think I will close this for now
