### ISSUE TITLE
Add instructions to how to contribute to the project

### ISSUE THREAD

**Issue by glauberramos** [funretro/distributed#43]

**Comment by pamo** [comment]
Would love to contribute.

**Comment by glauberramos** [comment]
Hi!

I am always open to contributions :D 

We have also a uservoice account that has some feedbacks from current users. Maybe you can work on one of those. What kind of help do you need?

Glauber

**Comment by pamo** [comment]
How do I get the tests to run? They're not passing on my machine when I run gulp test. There seems to be something wrong with the karma config.

**Comment by glauberramos** [comment]
I was not able to configure properly the tests, it still need some work on it.
