### ISSUE TITLE
Add start unit tests

### ISSUE THREAD

**Issue by glauberramos** [funretro/distributed#44]

**Comment by pamo** [comment]
I would prioritize this and #45 to make the codebase more approachable for contribution :fearful:

**Comment by glauberramos** [comment]
I added the priority labels to those 2 cards.

I agree they are priority. Also #43 is very important.

Do you want to work on those? Go ahead. It will be very helpful for the project :D

And thanks for the help so far.

**Comment by pamo** [comment]
I would except the fact that the code is untested makes it very difficult to understand. Don't really know where to start in terms of getting the tests to start :/

**Comment by glauberramos** [comment]
The code indeed lack tests and it may be difficult to understand. But at least is separated in small functions and that may help to test it. 

I will try to add some tests as well.

**Comment by pamo** [comment]
Did you see my pr #68? I was able to get the tests running last night.

**Comment by glauberramos** [comment]
Nice, I checked it quickly, but will look further this week.

**Comment by pamo** [comment]
Did you get a chance to look at it @glauberramos ?

**Comment by glauberramos** [comment]
Not really =/
I'll travel to the beach now and will be back on monday. I will take a look early next week.

**Comment by glauberramos** [comment]
Pull request accepted :dancer:
