### ISSUE TITLE
Fix headers with multiple lines

### ISSUE THREAD

**Issue by glauberramos** [funretro/distributed#49]

**Comment by pamo** [comment]
Should they truncate? Do you have an example?

**Comment by glauberramos** [comment]
The problem right now is how the cards are moving with the long text on the header ... I am not sure what is the solution to it, maybe truncating will help. Do you want to try some ideas on it? You can post them here on this thread.

<img width="764" alt="screen shot 2016-01-31 at 8 59 52 pm" src="https://cloud.githubusercontent.com/assets/559434/12706166/9a313ab0-c85d-11e5-9c58-4e9a57f4f85d.png">

**Comment by pamo** [comment]
Hmm, doesn't seem like a big problem to me. Have you gotten feedback around it? The quickest fix would be to truncate with CSS but you would have to decide at which point to truncate. Another option would be to use flexbox to get the row of column headers to grow together but that would require a lot of HTML restructuring.

**Comment by tympollack** [comment]
I feel that if a user wanted their text truncated, they'd shorten the text.  If you do go that route, you probably want to impose a character limit instead.  Otherwise, I think matching the sizing would be appropriate.

**Comment by pamo** [comment]
+1 to character limits. The current HTML structure is a repeated unordered list with a header per column created, which make sense to me. If we were to want each header to take the same vertical height, they would have to be a part of the same parent container outside of the context of their columns. This wouldn't make sense to me in a structural way as well as a programatic way (my first thought would be to have to ngRepeat for every column twice to generate a header and the list of cards).

**Comment by glauberramos** [comment]
I agree that this is not a big problem. I liked the idea about truncating the text, if you want to implement it go ahead :dancers:

**Comment by pamo** [comment]
Max length/width?

**Comment by glauberramos** [comment]
Max length I think it's better.

**Comment by pamo** [comment]
Yes but what should it be?

**Comment by glauberramos** [comment]
Let's not work on this for now, doesn't seen like a priority :smile:
