### ISSUE TITLE
Add ability to toggle Online/Offline mode

### ISSUE THREAD

**Issue by alvarocavalcanti** [funretro/distributed#56]
# Description

The top bar should have a button to toggle between online and offline mode.
# Motivation

When running a retrospective with a remote distributed team some activities like "One Word" and "Tell and Cluster" we felt the need to add cards to the board that should not be available to everyone right away.

**Comment by alvarocavalcanti** [comment]
This feature is similar to #63

**Comment by glauberramos** [comment]
@alvarocavalcanti #63 is done, do you fell it fulfils the need of an "offline" mode?

**Comment by alvarocavalcanti** [comment]
Yes, I do! I'll close this issue.
