### ISSUE TITLE
Ability to move cards between columns

### ISSUE THREAD

**Issue by alvarocavalcanti** [funretro/distributed#58]
# Description

There should be a way to move cards between columns
# Motivation

During "open canvas" style activities it's required for the users to place their cards on the wall and then have the latter moved/grouped.

The swapping could be done by either dragging or using left/right arrow buttons on each card.

**Comment by rajesh0706** [comment]
Is there any update on this issue Fix..

**Comment by glauberramos** [comment]
Implemented.
