### ISSUE TITLE
Add a button to remove all the cards.

### ISSUE THREAD

**Issue by guipdutra** [funretro/distributed#65]
I would like to remove all the cards after the retrospective end.

**Comment by pamo** [comment]
Per column or for the entire board?

**Comment by glauberramos** [comment]
I think #23 covers that, it is a feature to delete the whole board. I think we should implement something like github and have a danger zone:

<img width="763" alt="screen shot 2016-02-01 at 10 43 13 pm" src="https://cloud.githubusercontent.com/assets/559434/12737187/36cb61c0-c935-11e5-9889-8dbf4aaa358f.png">

What do you think?

**Comment by jesusmercado** [comment]
(+1) We have been using this for our retros and at the end we needed to delete all the cards at the end. @glauberramos I like something like the "Danger Zone".

**Comment by brunapereira** [comment]
@jesusmercado in this case, would you like to keep the columns added/changed?

**Comment by jesusmercado** [comment]
I would prefer leave the board how it was originally at the beginning (I believe it has 3 columns).
