### ISSUE TITLE
Move columns

### ISSUE THREAD

**Issue by glauberramos** [funretro/distributed#79]

**Comment by Bonifacio2** [comment]
Please!

**Comment by cjhowald** [comment]
It would be really great to be able to drag and drop columns. Otherwise, if you want to add a new column anywhere but in the last position, you have to first delete later columns and then recreate them. This is very inconvenient.

**Comment by Paarmita** [comment]
Can I take up this issue? I am a beginner in angular so it would be great if you could provide some help :)

**Comment by mariuslazar93** [comment]
The [angularjs-dragula](https://github.com/bevacqua/angularjs-dragula ) module could be of help with this task.

**Comment by Sneha-Watharkar** [comment]
Is this issue still open? Can I take it?

**Comment by PixleProgrambetaxl** [comment]
+1

**Comment by strobelt** [comment]
If this issue is still open I would like to help

**Comment by glauberramos** [comment]
It's open
