### ISSUE TITLE
Card Text Not Persisting

### ISSUE THREAD

**Issue by chapmanjw** [funretro/distributed#81]
When I save text into a card and then re-load the page, the cards are still there, but they are blank.

I've tested this with the github hosted version and running the code on OSX.  I've tested from Safari, Firefox, and Chrome.

**Comment by glauberramos** [comment]
I am looking at this issue now. I couldn't figure out what is happening yet.

I tried to use old versions of the code, change firebase app, still couldn't find.

Will keep you posted here about my progress...

**Comment by glauberramos** [comment]
Apparently it's an issue with backface-visibility that it is not working well on chrome. I disabled the card animation for now so it should work fine. I will work more on this later.

**Comment by chapmanjw** [comment]
I pulled the latest commit from master and I'm still seeing the issue locally.  Am I missing something there?

**Comment by chapmanjw** [comment]
Never mind, I see the other branch.  Working locally now.

**Comment by glauberramos** [comment]
Yeah master is still breaking, I will try to fix it this week

**Comment by chinaowl** [comment]
What branch should I be using?

**Comment by glauberramos** [comment]
gh-pages
